from typing import Optional


class User:
    def __init__(self, email: Optional[str] = None, pwdhash: Optional[str] = None, salt: Optional[str] = None):
        """User object

        Args:
            email (Optional[str], optional): User's email. Defaults to None.
            pwdhash (Optional[str], optional): Hashcode of the user's password. Defaults to None.
            salt (Optional[str], optional): Salt of the hashcode. Defaults to None.
        """
        self.email = email
        self.pwdhash = pwdhash
        self.salt = salt


class Group:
    def __init__(self, id: Optional[str] = None, members: list[str] = []):
        """Group object

        Args:
            id (Optional[str], optional): Group id generated by hashing the key of the group. Defaults to None.
            members (list[str], optional): List of group member's email. Defaults to [].
        """
        self.id = id
        self.members = members
